INSERT INTO STUDENT (ID, EXTERNAL_STUDENT_ID, FORENAME, SURNAME) VALUES (1, 'c7453423', 'Walter', 'White');
INSERT INTO STUDENT (ID, EXTERNAL_STUDENT_ID, FORENAME, SURNAME) VALUES (2, 'c3908978', 'Jesse', 'Pinkman');

